title: nninnis.dev
description: 개발 기록
url: https://nninnis.github.io
author:
  name: nninnis
lang: ko
timezone: Asia/Seoul

permalink: pretty

plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  releases:
    output: true
    permalink: /releases/:name/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default
  - scope:
      path: ""
      type: "releases"
    values:
      layout: release

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
